In [2]:
#Import Essential libraries
import numpy as np
import pandas as pd

In [4]:
#Read Dataset
df=pd.read_csv("dtsvm.csv")
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [12]:
#Separate dataset into independent & dependent variables
#Extracting independent variable X i.e. Gender & Age
X=df.iloc[:,[2,3]].values
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01,      nan],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [6]:
#Extracting dependent variable y i.e Purchased
y=df.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [7]:
#Checking for missing values
df.isnull().sum() #checking if missing values exist or not

User ID            0
Gender             0
Age                2
EstimatedSalary    2
Purchased          0
dtype: int64

In [14]:
#Handling missing values
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan, strategy='mean')
X=si.fit_transform(X)
X

array([[1.90000000e+01, 1.90000000e+04],
       [3.50000000e+01, 2.00000000e+04],
       [2.60000000e+01, 4.30000000e+04],
       [2.70000000e+01, 5.70000000e+04],
       [1.90000000e+01, 7.60000000e+04],
       [2.70000000e+01, 5.80000000e+04],
       [2.70000000e+01, 8.40000000e+04],
       [3.20000000e+01, 1.50000000e+05],
       [2.50000000e+01, 3.30000000e+04],
       [3.50000000e+01, 6.50000000e+04],
       [2.60000000e+01, 8.00000000e+04],
       [2.60000000e+01, 5.20000000e+04],
       [2.00000000e+01, 8.60000000e+04],
       [3.20000000e+01, 1.80000000e+04],
       [1.80000000e+01, 8.20000000e+04],
       [2.90000000e+01, 8.00000000e+04],
       [4.70000000e+01, 2.50000000e+04],
       [4.50000000e+01, 2.60000000e+04],
       [4.60000000e+01, 2.80000000e+04],
       [4.80000000e+01, 2.90000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.70000000e+01, 4.90000000e+04],
       [4.80000000e+01, 4.10000000e+04],
       [4.50000000e+01, 2.20000000e+04],
       [4.600000

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
X_train

array([[5.80000000e+01, 1.44000000e+05],
       [5.90000000e+01, 8.30000000e+04],
       [2.40000000e+01, 5.50000000e+04],
       [2.60000000e+01, 3.50000000e+04],
       [5.80000000e+01, 3.80000000e+04],
       [4.20000000e+01, 8.00000000e+04],
       [4.00000000e+01, 7.50000000e+04],
       [5.90000000e+01, 1.30000000e+05],
       [4.60000000e+01, 4.10000000e+04],
       [4.10000000e+01, 6.00000000e+04],
       [4.20000000e+01, 6.40000000e+04],
       [3.70000000e+01, 1.46000000e+05],
       [2.30000000e+01, 4.80000000e+04],
       [2.50000000e+01, 3.30000000e+04],
       [2.40000000e+01, 8.40000000e+04],
       [2.70000000e+01, 9.60000000e+04],
       [2.30000000e+01, 6.30000000e+04],
       [4.80000000e+01, 3.30000000e+04],
       [4.80000000e+01, 9.00000000e+04],
       [4.20000000e+01, 1.04000000e+05],
       [4.40000000e+01, 3.90000000e+04],
       [3.20000000e+01, 1.20000000e+05],
       [3.80000000e+01, 5.00000000e+04],
       [3.20000000e+01, 1.35000000e+05],
       [5.200000

In [18]:
X_test

array([[3.00000000e+01, 8.70000000e+04],
       [3.80000000e+01, 5.00000000e+04],
       [3.50000000e+01, 7.50000000e+04],
       [3.00000000e+01, 7.90000000e+04],
       [3.50000000e+01, 5.00000000e+04],
       [2.70000000e+01, 2.00000000e+04],
       [3.10000000e+01, 1.50000000e+04],
       [3.60000000e+01, 1.44000000e+05],
       [1.80000000e+01, 6.80000000e+04],
       [4.70000000e+01, 4.30000000e+04],
       [3.00000000e+01, 4.90000000e+04],
       [2.80000000e+01, 5.50000000e+04],
       [3.70000000e+01, 5.50000000e+04],
       [3.90000000e+01, 7.70000000e+04],
       [2.00000000e+01, 8.60000000e+04],
       [3.20000000e+01, 1.17000000e+05],
       [3.70000000e+01, 7.70000000e+04],
       [1.90000000e+01, 8.50000000e+04],
       [5.50000000e+01, 1.30000000e+05],
       [3.50000000e+01, 2.20000000e+04],
       [3.50000000e+01, 4.70000000e+04],
       [4.70000000e+01, 1.44000000e+05],
       [4.10000000e+01, 5.10000000e+04],
       [4.70000000e+01, 1.05000000e+05],
       [2.300000

In [19]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,

In [20]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [21]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)

In [23]:
#Applying SVM(Support Vector Machine) Algorithm 
from sklearn.svm import SVC #SVC-SupportVectorClassifier
svc=SVC(kernel="linear", random_state=0)
svc.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [24]:
#Do testing of model with testing dataset
y_pred=svc.predict(X_test)

In [25]:
y_pred #predicted values

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [26]:
y_test #original(test) values

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [28]:
#Matching predicted & test values
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm 

array([[52,  6],
       [ 3, 19]])